function eventos() {
	INICIO.onclick=function(){		
		$("#contenedor").load('formas/inicio.html');	
		$('#girar').fadeIn();		
	}
	LAEMPRESA.onclick=function(){		
		$("#contenedor").load('formas/laempresa.html');	
		$('#girar').fadeOut();
	}
	SERVICIOS.onclick=function(){		
		$("#contenedor").load('formas/servicios.html');	
		$('#girar').fadeOut();
	}
	CLIENTES.onclick=function(){		
		$("#contenedor").load('formas/clientes.html');	
		$('#girar').fadeOut();
	}
	VALORES.onclick=function(){		
		$("#contenedor").load('formas/valores.html');	
		$('#girar').fadeOut();
	}
	BLOG.onclick=function(){		
		$("#contenedor").load('formas/blog.html');	
		$('#girar').fadeOut();
	}
	CONTACTO.onclick=function(){		
		$("#contenedor").load('formas/contacto.html');	
		$('#girar').fadeOut();
	}

	minicio.onclick=function(){		
		$("#contenedor").load('formas/inicio.html');	
		$('#girar').fadeIn();
	}
	mlaempresa.onclick=function(){		
		$("#contenedor").load('formas/laempresa.html');	
		$('#girar').fadeOut();
	}
	mservicios.onclick=function(){		
		$("#contenedor").load('formas/servicios.html');	
		$('#girar').fadeOut();
	}
	mclientes.onclick=function(){		
		$("#contenedor").load('formas/clientes.html');	
		$('#girar').fadeOut();
	}
	mvalores.onclick=function(){		
		$("#contenedor").load('formas/valores.html');	
		$('#girar').fadeOut();
	}
	mblog.onclick=function(){		
		$("#contenedor").load('formas/blog.html');	
		$('#girar').fadeOut();
	}
	mcontacto.onclick=function(){		
		$("#contenedor").load('formas/contacto.html');	
		$('#girar').fadeOut();
	}
}